const personalBio = [
    "I'm a Full-Stack Developer with a strong passion in database architecture and optimization. I've designed and implemented end-to-end applications, integrating solutions across the entire software stack, and successfully reduced an average 45% in query execution time through database optimization. My focus on continual learning drives me to deliver impactful and scalable software solutions.",
    "My tech stack includes MySQL, MongoDB, PHP, Node.js, Express, React, JavaScript, jQuery, HTML, CSS, Bootstrap, Tailwind, RESTful API, Git, and Agile. I'm also proficient in WordPress CMS. Throughout my career, I have experience in developing IoT Monitoring System, E-Claim System, and Project Management System. I always strive to build systems and applications that are impactful, user-friendly, and scalable.",
    "Apart from my technical skills, my strong adaptability is my secret weapon because it helps me quickly grasp new technologies, adjust to different project settings, and adapt to changing requirements. I'm the kind of person who can work both independently and as part of a team.",
    "Outside of my job, I'm really into photography. I enjoy capturing landscapes, people, and animals, which allows me to express my creativity and attention to detail in a different way. In addition to photography, I have a passion for both indoor and outdoor sports such as badminton, tennis, jogging, swimming, hiking.",
    "Aside from my love for sports, I spend some time for volunteering. One of my most rewarding experiences is participating in initiatives aimed at helping and serving the homeless and marginalised communities. I contributed to food distribution for homeless individuals. Volunteering in animal welfare is another cause close to my heart, as I believe in advocating for the well-being of our furry friends. Furthermore, I involved in beach cleaning activities to contribute to environmental conservation. Participating in these cleanups not only allows me to enjoy the natural beauty of our beaches but also instills a sense of responsibility towards the environment.",
];

export default personalBio;
